### ISSUE TITLE
update composer

### ISSUE THREAD

**Issue by lorvent** [twinslab/blog#1]
Hi,
please update composer.json to take stable build instead of  dev builds

also, why don't you use sluggable composer package?

**Comment by grrnikos** [comment]
Thanks. I have updated composer to use stable builds. 

Please note that this project is currently in development, and there are entire parts that are missing right now (no search, no comments etc)

As for sluggable, we still want to test if it fits our needs :)

**Comment by lorvent** [comment]
i understand its still under development but i can see good potential in it :)
